
Neos:
  EventSourcing:
    EventStore:
      storage:
        options:
          eventTableName: neos_eventsourcing_eventstore_events
          backendOptions:
            driver: pdo_mysql
            host: 127.0.0.1
            dbname: null
            user: null
            password: null
            charset: utf8
  Flow:
    persistence:
      doctrine:
        migrations:
          ignoredTables:
            neos_eventsourcing_eventstore_events: true
