Neos:
  Cqrs:
    EventStore:
      storage:
        options:
          eventTableName: 'neos_cqrs_events'

          backendOptions:
            driver: 'pdo_mysql'
            host: '127.0.0.1'
            dbname: NULL
            user: NULL
            password: NULL
            charset: 'utf8'

          mappingTypes:
            'datetime_micro':
              dbType: 'datetime'
              className: 'Neos\Cqrs\EventStore\Storage\Doctrine\DataTypes\DateTimeType'
